[package]
name = "lexer"
version = "0.1.0"
authors = ["AndrewGrim <39337035+AndrewGrim@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "lexer"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.8.4"
features = ["extension-module"]

[dependencies.regex]
version = "1.3.3"