from enum import IntEnum

class STYLE(IntEnum):
	TEXT = 0
	HEADING = 1
	HIDDEN = 3
	CODE = 4
	SYMBOL = 5
	TEST = 6
	STRIKE = 7
	BOLD = 8
	UNDERLINE = 9
	ITALIC = 11
	IMAGE = 12
	LINK = 13
	HTML = 14
	HTML_ATTRIBUTE = 15
	FORMAT = 16

	CODEBLOCK_KEYWORD = 17
	CODEBLOCK_SYMBOL = 18
	CODEBLOCK_TEXT = 19
	CODEBLOCK_STRING = 20
	CODEBLOCK_COMMENT = 21
	CODEBLOCK_FUNCTION = 22
	CODEBLOCK_CLASS = 23
	CODEBLOCK_TYPE = 24
	CODEBLOCK_FLOW = 25
	CODEBLOCK_DIGIT = 26

	COMMENT = 27
	LINK_UNDERLINED = 28
	IMAGE_UNDERLINED = 29

class INDICATOR(IntEnum):
	ERROR = 32