from enum import IntEnum

class STYLE(IntEnum):
	TEXT = 0
	HEADING = 1
	HIDDEN = 2
	CODE = 3
	SYMBOL = 4
	TEST = 5
	STRIKE = 6
	BOLD = 7
	UNDERLINE = 8
	ITALIC = 9
	IMAGE = 10
	LINK = 11
	HTML = 12
	HTML_ATTRIBUTE = 13
	FORMAT = 14

	CODEBLOCK_KEYWORD = 15
	CODEBLOCK_SYMBOL = 16
	CODEBLOCK_TEXT = 17
	CODEBLOCK_STRING = 18
	CODEBLOCK_COMMENT = 19
	CODEBLOCK_FUNCTION = 20
	CODEBLOCK_CLASS = 21
	CODEBLOCK_TYPE = 22
	CODEBLOCK_FLOW = 23
	CODEBLOCK_DIGIT = 24

	COMMENT = 25
	LINK_UNDERLINED = 26
	IMAGE_UNDERLINED = 27

class INDICATOR(IntEnum):
	ERROR = 32